
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 10.1.03 EDK_K_SP3.6
* DO NOT EDIT.
*
* Copyright (c) 2005 Xilinx, Inc.  All rights reserved. 
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[] =
{
	{
		XPAR_LEDS_4BIT_DEVICE_ID,
		XPAR_LEDS_4BIT_BASEADDR,
		XPAR_LEDS_4BIT_INTERRUPT_PRESENT,
		XPAR_LEDS_4BIT_IS_DUAL
	},
	{
		XPAR_FORWARD_DEVICE_ID,
		XPAR_FORWARD_BASEADDR,
		XPAR_FORWARD_INTERRUPT_PRESENT,
		XPAR_FORWARD_IS_DUAL
	},
	{
		XPAR_BACKWARD_DEVICE_ID,
		XPAR_BACKWARD_BASEADDR,
		XPAR_BACKWARD_INTERRUPT_PRESENT,
		XPAR_BACKWARD_IS_DUAL
	},
	{
		XPAR_MOTORSEQ_DEVICE_ID,
		XPAR_MOTORSEQ_BASEADDR,
		XPAR_MOTORSEQ_INTERRUPT_PRESENT,
		XPAR_MOTORSEQ_IS_DUAL
	},
	{
		XPAR_HALT_DEVICE_ID,
		XPAR_HALT_BASEADDR,
		XPAR_HALT_INTERRUPT_PRESENT,
		XPAR_HALT_IS_DUAL
	}
};


