
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 10.1 EDK_K.15
* DO NOT EDIT.
*
* Copyright (c) 2005 Xilinx, Inc.  All rights reserved. 
* 
* Description: Driver parameters
*
*******************************************************************/

#define STDIN_BASEADDRESS 0x84000000
#define STDOUT_BASEADDRESS 0x84000000

/******************************************************************/


/* Definitions for peripheral XPS_BRAM_IF_CNTLR_1 */
#define XPAR_XPS_BRAM_IF_CNTLR_1_BASEADDR 0xFFFF8000
#define XPAR_XPS_BRAM_IF_CNTLR_1_HIGHADDR 0xFFFFFFFF


/******************************************************************/

/* Definitions for driver UARTLITE */
#define XPAR_XUARTLITE_NUM_INSTANCES 1

/* Definitions for peripheral RS232_UART_1 */
#define XPAR_RS232_UART_1_BASEADDR 0x84000000
#define XPAR_RS232_UART_1_HIGHADDR 0x8400FFFF
#define XPAR_RS232_UART_1_DEVICE_ID 0
#define XPAR_RS232_UART_1_BAUDRATE 9600
#define XPAR_RS232_UART_1_USE_PARITY 0
#define XPAR_RS232_UART_1_ODD_PARITY 0
#define XPAR_RS232_UART_1_DATA_BITS 8


/******************************************************************/


/* Canonical definitions for peripheral RS232_UART_1 */
#define XPAR_UARTLITE_0_DEVICE_ID XPAR_RS232_UART_1_DEVICE_ID
#define XPAR_UARTLITE_0_BASEADDR 0x84000000
#define XPAR_UARTLITE_0_HIGHADDR 0x8400FFFF
#define XPAR_UARTLITE_0_BAUDRATE 9600
#define XPAR_UARTLITE_0_USE_PARITY 0
#define XPAR_UARTLITE_0_ODD_PARITY 0
#define XPAR_UARTLITE_0_DATA_BITS 8
#define XPAR_UARTLITE_0_SIO_CHAN 0


/******************************************************************/

#define XPAR_CPU_PPC405_CORE_CLOCK_FREQ_HZ 100000000

/******************************************************************/

#define XPAR_CPU_ID 0
#define XPAR_PPC405_ID 0
#define XPAR_PPC405_CORE_CLOCK_FREQ_HZ 100000000
#define XPAR_PPC405_DPLB0_DWIDTH 64
#define XPAR_PPC405_DPLB0_NATIVE_DWIDTH 64
#define XPAR_PPC405_IPLB0_DWIDTH 64
#define XPAR_PPC405_IPLB0_NATIVE_DWIDTH 64
#define XPAR_PPC405_DPLB1_DWIDTH 64
#define XPAR_PPC405_DPLB1_NATIVE_DWIDTH 64
#define XPAR_PPC405_IPLB1_DWIDTH 64
#define XPAR_PPC405_IPLB1_NATIVE_DWIDTH 64
#define XPAR_PPC405_DPLB1_ADDR_BASE 0xffffffff
#define XPAR_PPC405_DPLB1_ADDR_HIGH 0x00000000
#define XPAR_PPC405_IPLB1_ADDR_BASE 0xffffffff
#define XPAR_PPC405_IPLB1_ADDR_HIGH 0x00000000
#define XPAR_PPC405_FASTEST_PLB_CLOCK DPLB0
#define XPAR_PPC405_GENERATE_PLB_TIMESPECS 1
#define XPAR_PPC405_DPLB0_P2P 0
#define XPAR_PPC405_DPLB1_P2P 1
#define XPAR_PPC405_IPLB0_P2P 0
#define XPAR_PPC405_IPLB1_P2P 1
#define XPAR_PPC405_ISOCM_DCR_BASEADDR 0x00000010
#define XPAR_PPC405_ISOCM_DCR_HIGHADDR 0x00000013
#define XPAR_PPC405_DSOCM_DCR_BASEADDR 0x00000020
#define XPAR_PPC405_DSOCM_DCR_HIGHADDR 0x00000023
#define XPAR_PPC405_DISABLE_OPERAND_FORWARDING 1
#define XPAR_PPC405_MMU_ENABLE 1
#define XPAR_PPC405_DETERMINISTIC_MULT 0
#define XPAR_PPC405_DCR_RESYNC 0
#define XPAR_PPC405_HW_VER "3.00.a"

/******************************************************************/

