
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 10.1.03 EDK_K_SP3.6
* DO NOT EDIT.
*
* Copyright (c) 2005 Xilinx, Inc.  All rights reserved. 
* 
* Description: Driver parameters
*
*******************************************************************/

#define STDIN_BASEADDRESS 0x84000000
#define STDOUT_BASEADDRESS 0x84000000

/******************************************************************/


/* Definitions for peripheral XPS_BRAM_IF_CNTLR_1 */
#define XPAR_XPS_BRAM_IF_CNTLR_1_BASEADDR 0xFFFFC000
#define XPAR_XPS_BRAM_IF_CNTLR_1_HIGHADDR 0xFFFFFFFF


/******************************************************************/

/* Definitions for driver UARTLITE */
#define XPAR_XUARTLITE_NUM_INSTANCES 1

/* Definitions for peripheral RS232_UART_1 */
#define XPAR_RS232_UART_1_BASEADDR 0x84000000
#define XPAR_RS232_UART_1_HIGHADDR 0x8400FFFF
#define XPAR_RS232_UART_1_DEVICE_ID 0
#define XPAR_RS232_UART_1_BAUDRATE 9600
#define XPAR_RS232_UART_1_USE_PARITY 0
#define XPAR_RS232_UART_1_ODD_PARITY 0
#define XPAR_RS232_UART_1_DATA_BITS 8


/******************************************************************/


/* Canonical definitions for peripheral RS232_UART_1 */
#define XPAR_UARTLITE_0_DEVICE_ID XPAR_RS232_UART_1_DEVICE_ID
#define XPAR_UARTLITE_0_BASEADDR 0x84000000
#define XPAR_UARTLITE_0_HIGHADDR 0x8400FFFF
#define XPAR_UARTLITE_0_BAUDRATE 9600
#define XPAR_UARTLITE_0_USE_PARITY 0
#define XPAR_UARTLITE_0_ODD_PARITY 0
#define XPAR_UARTLITE_0_DATA_BITS 8
#define XPAR_UARTLITE_0_SIO_CHAN 0


/******************************************************************/

/* Definitions for driver GPIO */
#define XPAR_XGPIO_NUM_INSTANCES 5

/* Definitions for peripheral LEDS_4BIT */
#define XPAR_LEDS_4BIT_BASEADDR 0x81420000
#define XPAR_LEDS_4BIT_HIGHADDR 0x8142FFFF
#define XPAR_LEDS_4BIT_DEVICE_ID 0
#define XPAR_LEDS_4BIT_INTERRUPT_PRESENT 0
#define XPAR_LEDS_4BIT_IS_DUAL 0


/* Definitions for peripheral FORWARD */
#define XPAR_FORWARD_BASEADDR 0x81460000
#define XPAR_FORWARD_HIGHADDR 0x8146FFFF
#define XPAR_FORWARD_DEVICE_ID 1
#define XPAR_FORWARD_INTERRUPT_PRESENT 0
#define XPAR_FORWARD_IS_DUAL 0


/* Definitions for peripheral BACKWARD */
#define XPAR_BACKWARD_BASEADDR 0x81440000
#define XPAR_BACKWARD_HIGHADDR 0x8144FFFF
#define XPAR_BACKWARD_DEVICE_ID 2
#define XPAR_BACKWARD_INTERRUPT_PRESENT 0
#define XPAR_BACKWARD_IS_DUAL 0


/* Definitions for peripheral MOTORSEQ */
#define XPAR_MOTORSEQ_BASEADDR 0x81480000
#define XPAR_MOTORSEQ_HIGHADDR 0x8148FFFF
#define XPAR_MOTORSEQ_DEVICE_ID 3
#define XPAR_MOTORSEQ_INTERRUPT_PRESENT 0
#define XPAR_MOTORSEQ_IS_DUAL 0


/* Definitions for peripheral HALT */
#define XPAR_HALT_BASEADDR 0x81400000
#define XPAR_HALT_HIGHADDR 0x8140FFFF
#define XPAR_HALT_DEVICE_ID 4
#define XPAR_HALT_INTERRUPT_PRESENT 0
#define XPAR_HALT_IS_DUAL 0


/******************************************************************/

#define XPAR_CPU_PPC405_CORE_CLOCK_FREQ_HZ 100000000

/******************************************************************/

#define XPAR_CPU_ID 0
#define XPAR_PPC405_ID 0
#define XPAR_PPC405_CORE_CLOCK_FREQ_HZ 100000000
#define XPAR_PPC405_DPLB0_DWIDTH 64
#define XPAR_PPC405_DPLB0_NATIVE_DWIDTH 64
#define XPAR_PPC405_IPLB0_DWIDTH 64
#define XPAR_PPC405_IPLB0_NATIVE_DWIDTH 64
#define XPAR_PPC405_DPLB1_DWIDTH 64
#define XPAR_PPC405_DPLB1_NATIVE_DWIDTH 64
#define XPAR_PPC405_IPLB1_DWIDTH 64
#define XPAR_PPC405_IPLB1_NATIVE_DWIDTH 64
#define XPAR_PPC405_DPLB1_ADDR_BASE 0xffffffff
#define XPAR_PPC405_DPLB1_ADDR_HIGH 0x00000000
#define XPAR_PPC405_IPLB1_ADDR_BASE 0xffffffff
#define XPAR_PPC405_IPLB1_ADDR_HIGH 0x00000000
#define XPAR_PPC405_FASTEST_PLB_CLOCK DPLB0
#define XPAR_PPC405_GENERATE_PLB_TIMESPECS 1
#define XPAR_PPC405_DPLB0_P2P 0
#define XPAR_PPC405_DPLB1_P2P 1
#define XPAR_PPC405_IPLB0_P2P 0
#define XPAR_PPC405_IPLB1_P2P 1
#define XPAR_PPC405_ISOCM_DCR_BASEADDR 0x00000010
#define XPAR_PPC405_ISOCM_DCR_HIGHADDR 0x00000013
#define XPAR_PPC405_DSOCM_DCR_BASEADDR 0x00000020
#define XPAR_PPC405_DSOCM_DCR_HIGHADDR 0x00000023
#define XPAR_PPC405_DISABLE_OPERAND_FORWARDING 1
#define XPAR_PPC405_MMU_ENABLE 1
#define XPAR_PPC405_DETERMINISTIC_MULT 0
#define XPAR_PPC405_DCR_RESYNC 0
#define XPAR_PPC405_HW_VER "3.00.a"

/******************************************************************/

