#################################################################
# Makefile generated by Xilinx Platform Studio 
# Project:C:\Users\DELL\Desktop\Motor_New\motor_new\uart\uart\uart.xmp
#
# WARNING : This file will be re-generated every time a command
# to run a make target is invoked. So, any changes made to this  
# file manually, will be lost when make is invoked next. 
#################################################################

XILINX_EDK_DIR = /cygdrive/c/Xilinx/10.1/EDK
NON_CYG_XILINX_EDK_DIR = C:/Xilinx/10.1/EDK

SYSTEM = uart

MHSFILE = uart.mhs

MSSFILE = uart.mss

FPGA_ARCH = virtex2p

DEVICE = xc2vp30ff896-7

LANGUAGE = vhdl

SEARCHPATHOPT = 

SUBMODULE_OPT = 

PLATGEN_OPTIONS = -p $(DEVICE) -lang $(LANGUAGE) $(SEARCHPATHOPT) $(SUBMODULE_OPT)

LIBGEN_OPTIONS = -mhs $(MHSFILE) -p $(DEVICE) $(SEARCHPATHOPT)

VPGEN_OPTIONS = -p $(DEVICE) $(SEARCHPATHOPT)

MANAGE_FASTRT_OPTIONS = -reduce_fanout no

OBSERVE_PAR_OPTIONS = -error yes

UART_OUTPUT_DIR = uart
UART_OUTPUT = $(UART_OUTPUT_DIR)/executable.elf

MICROBLAZE_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/microblaze/mb_bootloop.elf
PPC405_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc405/ppc_bootloop.elf
PPC440_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc440/ppc440_bootloop.elf
BOOTLOOP_DIR = bootloops

PPC405_0_BOOTLOOP = $(BOOTLOOP_DIR)/ppc405_0.elf

BRAMINIT_ELF_FILES =  $(UART_OUTPUT) 
BRAMINIT_ELF_FILE_ARGS =   -pe ppc405_0 $(UART_OUTPUT) 

ALL_USER_ELF_FILES = $(UART_OUTPUT) 

SIM_CMD = vsim

BEHAVIORAL_SIM_SCRIPT = simulation/behavioral/$(SYSTEM)_setup.do

STRUCTURAL_SIM_SCRIPT = simulation/structural/$(SYSTEM)_setup.do

TIMING_SIM_SCRIPT = simulation/timing/$(SYSTEM)_setup.do

DEFAULT_SIM_SCRIPT = $(BEHAVIORAL_SIM_SCRIPT)

MIX_LANG_SIM_OPT = -mixed yes

SIMGEN_OPTIONS = -p $(DEVICE) -lang $(LANGUAGE) $(SEARCHPATHOPT) $(BRAMINIT_ELF_FILE_ARGS) $(MIX_LANG_SIM_OPT)  -s mti -X C:/Users/DELL/Desktop/Motor_New/motor_new/uart/uart/ -E C:/Users/DELL/Desktop/Motor_New/motor_new/uart/uart/


LIBRARIES =  \
       ppc405_0/lib/libxil.a 
VPEXEC = virtualplatform/vpexec.exe

LIBSCLEAN_TARGETS = ppc405_0_libsclean 

PROGRAMCLEAN_TARGETS = uart_programclean 

CORE_STATE_DEVELOPMENT_FILES = 

WRAPPER_NGC_FILES = implementation/ppc405_0_wrapper.ngc \
implementation/jtagppc_cntlr_0_wrapper.ngc \
implementation/plb0_wrapper.ngc \
implementation/xps_bram_if_cntlr_1_wrapper.ngc \
implementation/plb_bram_if_cntlr_1_bram_wrapper.ngc \
implementation/rs232_uart_1_wrapper.ngc \
implementation/clock_generator_0_wrapper.ngc \
implementation/proc_sys_reset_0_wrapper.ngc

POSTSYN_NETLIST = implementation/$(SYSTEM).ngc

SYSTEM_BIT = implementation/$(SYSTEM).bit

DOWNLOAD_BIT = implementation/download.bit

SYSTEM_ACE = implementation/$(SYSTEM).ace

UCF_FILE = data/uart.ucf

BMM_FILE = implementation/$(SYSTEM).bmm

BITGEN_UT_FILE = etc/bitgen.ut

XFLOW_OPT_FILE = etc/fast_runtime.opt
XFLOW_DEPENDENCY = __xps/xpsxflow.opt $(XFLOW_OPT_FILE)

XPLORER_DEPENDENCY = __xps/xplorer.opt
XPLORER_OPTIONS = -p $(DEVICE) -uc $(SYSTEM).ucf -bm $(SYSTEM).bmm -max_runs 7

FPGA_IMP_DEPENDENCY = $(BMM_FILE) $(POSTSYN_NETLIST) $(UCF_FILE) $(BITGEN_UT_FILE) $(XFLOW_DEPENDENCY)

#################################################################
# SOFTWARE APPLICATION UART
#################################################################

UART_SOURCES = /cygdrive/c/Users/DELL/Desktop/Motor_New/motor_new/uart/uart/uart.c 

UART_HEADERS = /cygdrive/c//Users/DELL/Desktop/Motor_New/motor_new/uart/uart/ppc405_0/include/xuartlite.h 

UART_CC = powerpc-eabi-gcc
UART_CC_SIZE = powerpc-eabi-size
UART_CC_OPT = -O2
UART_CFLAGS = 
UART_CC_SEARCH = # -B
UART_LIBPATH = -L./ppc405_0/lib/ # -L
UART_INCLUDES = -I./ppc405_0/include/  -Ippc405_0/include/ # -I
UART_LFLAGS = # -l
UART_LINKER_SCRIPT = 
UART_LINKER_SCRIPT_FLAG = #-Wl,-T -Wl,$(UART_LINKER_SCRIPT) 
UART_CC_DEBUG_FLAG =  -g 
UART_CC_PROFILE_FLAG = # -pg
UART_CC_GLOBPTR_FLAG= # -msdata=eabi
UART_CC_INFERRED_FLAGS= 
UART_CC_START_ADDR_FLAG=  # -Wl,-defsym -Wl,_START_ADDR=
UART_CC_STACK_SIZE_FLAG=  # -Wl,-defsym -Wl,_STACK_SIZE=
UART_CC_HEAP_SIZE_FLAG=  # -Wl,-defsym -Wl,_HEAP_SIZE=
UART_OTHER_CC_FLAGS= $(UART_CC_GLOBPTR_FLAG)  \
                  $(UART_CC_START_ADDR_FLAG) $(UART_CC_STACK_SIZE_FLAG) $(UART_CC_HEAP_SIZE_FLAG)  \
                  $(UART_CC_INFERRED_FLAGS)  \
                  $(UART_LINKER_SCRIPT_FLAG) $(UART_CC_DEBUG_FLAG) $(UART_CC_PROFILE_FLAG) 
